
#pragma once

#define MAURO_GL_CONTEXT_VERSION_MAJOR 3
#define MAURO_GL_CONTEXT_VERSION_MINOR 3

#define MAURO_GL_SHARED_WINDOW_WIDTH  1204
#define MAURO_GL_SHARED_WINDOW_HEIGHT 768

#define MAURO_GL_CHILD_WINDOW_DEFAULT_WIDTH  400
#define MAURO_GL_CHILD_WINDOW_DEFAULT_HEIGHT 400